@baseUrl = http://localhost:3000

### Get all films
GET {{baseUrl}}/films

GET {{baseUrl}}/3

### Get all films with a minimum duration of 120 minutes
GET {{baseUrl}}/films?minimum-duration=120

### Add a new film
###The data I’m sending you is in JSON (JavaScript Object Notation) format
POST {{baseUrl}}/films
Content-Type: application/json

{
  "title": "Past Lives",
  "director": "Celine Song",
  "duration": 105,
  "budget": 1000000,
  "imageUrl": "https://example.com/pastlives.jpg"
}


